{{- if and .Values.ui.enabled (not .Values.ui.existingSecret) }}
{{- if or .Values.ui.env.authSecret .Values.ui.keycloak.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "goff-manager.ui.secretName" . }}
  namespace: {{ include "goff-manager.namespace" . }}
  labels:
    {{- include "goff-manager.ui.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.ui.env.authSecret }}
  {{ .Values.ui.authSecretKey | default "auth-secret" }}: {{ .Values.ui.env.authSecret | b64enc | quote }}
  {{- end }}
  {{- if and .Values.ui.keycloak.enabled .Values.ui.keycloak.clientSecret }}
  {{ .Values.ui.keycloakSecretKey | default "keycloak-client-secret" }}: {{ .Values.ui.keycloak.clientSecret | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
