{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "goff-manager.api.fullname" . }}
  namespace: {{ include "goff-manager.namespace" . }}
  labels:
    {{- include "goff-manager.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.api.service.type "NodePort") .Values.api.service.nodePort }}
      nodePort: {{ .Values.api.service.nodePort }}
      {{- end }}
  selector:
    {{- include "goff-manager.api.selectorLabels" . | nindent 4 }}
{{- end }}
