{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "goff-manager.ui.fullname" . }}
  namespace: {{ include "goff-manager.namespace" . }}
  labels:
    {{- include "goff-manager.ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.ui.service.type "NodePort") .Values.ui.service.nodePort }}
      nodePort: {{ .Values.ui.service.nodePort }}
      {{- end }}
  selector:
    {{- include "goff-manager.ui.selectorLabels" . | nindent 4 }}
{{- end }}
